cloudflare/workers-rs

- rust-sandbox/src/lib.rs
Follow-up to https://github.com/cloudflare/workers-rs/pull/16#issuecomment-908440475.
> Remove unnecessary clone in rust-sandbox

- worker-sandbox/src/lib.rs
- worker/src/request_init.rs
> fix RequestInit, update default props

- worker-build/src/main.rs
Previously `worker-build` emitted JavaScript files using the `esmodule` syntax in a `.mjs` file so they could be loaded without being explicitly marked as `esmodule` in the wrangler file. This caused issues in #63 where snippets weren't renamed because import statements would have to change, so instead now we don't rename anything to `.mjs` and explicitly mark all JavaScript files in the `wrangler.toml` file as `ESModule` as shown in [this example project](https://github.com/zebp/inline-js-example/blob/esmodule/wrangler.toml#L23).
One problem is that if this version is ever published under `worker-build` any project using an outdated version of the workers crate would install the latest version when compiling, emitting an invalid output for their wrangler config. The update `worked-build` …
> fix: don't rename to mjs

- worker/src/request.rs
Which already works for responses
> Allow to debug-print requests

- README.md
They're not beta anymore woohoo
> Remove beta warning for durable objects in README.md

- worker-macros/src/event.rs
This fixes the event macro to not depend on global symbols, instead use the absolute module path of the worker crate. This simplifies the import and basically makes it possible to not *-use the workers crate.
This might be considered a breaking change, if anyone is depending on the generated wasm wrapper function.
Before:
```rust
use worker::*;
#[event(fetch)]
pub async main(req: Request, env: Env) -> Result<Response> {
Response::empty()
}
```
After:
```rust
use worker::{event, Env, Request, Response};
#[event(fetch)]
pub async main(req: Request, env: Env) -> Result<Response> {
Response::empty()
}
```
I also updated the "scheduled", but there seems to be more broken (e.g. worker::Schedule doesnt seem to exist in the first place).
> Fixes module references in event macro

- worker-macros/src/durable_object.rs
- worker-macros/src/event.rs
- worker-macros/src/lib.rs
- worker-sandbox/src/counter.rs
- worker-sandbox/src/lib.rs
- worker-sys/src/lib.rs
- worker-sys/src/schedule.rs
- worker/src/env.rs
- worker/src/formdata.rs
- worker/src/lib.rs
- worker/src/request.rs
- worker/src/request_init.rs
- worker/src/response.rs
- worker/src/router.rs
- worker/src/schedule.rs
Fixes any clippy lints or formatting mistakes in an effort to close #58.
> Fix formatting and clippy lints

- worker/src/request_init.rs
> fix: allow for negative cache TTL by status

- Cargo.lock
- worker-build/Cargo.toml
- worker/src/global.rs
Fixes various CI errors caused by updates to clippy and crates in the dep tree.
> fix ci errors

- worker/src/durable.rs
`From<Duration>` and `From<i64>` for `ScheduledTime` interpret the
inputs as timestamps (in particular, the number of milliseconds since
the UNIX epoch). Based on the test case in worker-sandbox
("durable_alarm"), the intention appears to interpret these as offsets
relative to the current time. This change aligns these methods with this
expectation.
> `durable::ScheduledTime`: Properly compute offsets

- Cargo.lock
- worker-sandbox/src/alarm.rs
- worker-sandbox/src/counter.rs
- worker-sandbox/src/lib.rs
- worker-sandbox/src/test/export_durable_object.rs
- worker-sandbox/tests/util.rs
- worker/src/durable.rs
- worker/src/error.rs
It seems that clippy has introduced new lints that now warn on various places in the codebase.
> chore: fix clippy lints

- worker-sys/Cargo.toml
- worker/Cargo.toml
Added some `web-sys` features that have been missed
> missing features from web-sys

- worker/src/response.rs
See https://github.com/cloudflare/workers-rs/pull/115 for more details.
Fixes https://github.com/cloudflare/workers-rs/issues/64 which re-emerged in 0.0.14.
> Fix response mangling in 0.0.14 by bringing back an accidentally rolled back fix from #115

- worker/src/response.rs
> fix: UAF when creating web_sys::Responses

- README.md
**🔖 Summary**
This commit adds some documentation to the README on how to configure the latest version of Miniflare (`3.0.1` at the time of writing) to test Rust-based, WASM-generated workers programatically in JavaScript / TypeScript tests.
> Add documentation for testing using Miniflare

- worker-build/src/main.rs
- worker-sandbox/src/r2.rs
- worker-sys/src/types/queue.rs
- worker/src/formdata.rs
- worker/src/headers.rs
- worker/src/r2/builder.rs
- worker/src/r2/mod.rs
- worker/src/request_init.rs
- worker/src/router.rs
- worker/src/websocket.rs
Just various typo fixes I found around the codebase whilst working on another PR.
> chore: various typo fixes

- examples/tracing/src/lib.rs
Multiple calls to `init` will cause a panic because a tracing subscriber has already been set globally.
> fix panic in tracing example

- worker-sys/src/ext/response.rs
> Correct typo in response webSocket attribute

- worker/src/durable.rs
Clarify that offset is in milliseconds in ScheduledTime
> Clarify units of offset in ScheduledTime

- worker/src/d1/mod.rs
> Add clone to D1PreparedStatement

- Cargo.lock
- Cargo.toml
See https://github.com/chronotope/chrono-tz/issues/152
> Pin chrono

- .github/workflows/create-release-pr.yml
Context: https://github.com/cloudflare/workers-rs/pull/512#issuecomment-2027472024
> Fix feature group for cargo-semver-check

- Cargo.toml
- worker/Cargo.toml
- worker/src/cf.rs
> Make chrono-tz an optional dependency

- package-lock.json
- worker-sandbox/Cargo.toml
- worker-sandbox/src/d1.rs
- worker-sandbox/src/lib.rs
- worker-sandbox/src/router.rs
- worker-sandbox/src/socket.rs
- worker-sandbox/tests/mf-socket.ts
- worker-sandbox/tests/socket.spec.ts
- worker-sys/src/types/socket.rs
- worker/src/socket.rs
Add tests for:
* Socket fails to connect and `opened` promise returns error
* Socket connects, echos data, and closes. 
cc @Kakapio
> Add socket tests

- worker/src/websocket.rs
> Fix issue with data corruption in web_sys::WebSocket

- templates/axum/src/lib.rs
I've fixed build error in the generated code.
Fix https://github.com/cloudflare/workers-rs/issues/571
> Fix templates/axum build error

- templates/axum/.gitignore
- templates/hello-world-http/.gitignore
- templates/hello-world/.gitignore
Fix https://github.com/cloudflare/workers-rs/issues/573
I have added .wrangler and node_modules to the .gitignore template.
These files are created when npx wrangler dev is run.
> Add some files to gitignore template

- Cargo.lock
- worker-build/Cargo.toml
- worker-build/src/install.rs
- worker-build/src/main.rs
> Use `wasm-pack` as crate dependency

- worker/src/lib.rs
Same issue as https://github.com/cloudflare/workers-rs/pull/584
> Publicly expose VersionMetadataBinding

- templates/leptos/cargo-generate.toml
This appears to fix #731 for me.
> Exclude .ico files from templating

- .github/workflows/create-release-pr.yml
Fix cargo release install in release PR GitHub workflow.
> ci: fix create release pr script

- Cargo.lock
- Cargo.toml
- worker-sandbox/Cargo.toml
Updates to the latest `wasm-bindgen@0.2.101`.
> wasm-bindgen@0.2.101

- Cargo.lock
- Cargo.toml
> wasm-bindgen@0.2.103

- worker-build/src/install.rs
This fixes the esbuild installation to ensure our expected esbuild version is installed and used.
> Fix esbuild install
