- README.md
- libworker/src/env.rs
- libworker/src/error.rs
- libworker/src/lib.rs
- libworker/src/router.rs
- rust-sandbox/Cargo.toml
- rust-sandbox/src/lib.rs
- `Router::new` now must be constructed with some shared data, either your own type, or a `()` stub to define the generic type parameter. I'd be happy to know how this can be avoided.. 
- `Router` methods return `Self` now so routes can be chained.
- All `Env` access is done though the `RouteContex`, a `ctx` param in the route fn. 
```rust
use worker::*;
#[event(fetch, respond_with_errors)]
pub async fn main(req: Request, env: Env) -> Result<Response> {
utils::set_panic_hook();
let router = Router::new(()); 
router
.on_async("/durable", |_req, ctx| async move {
let namespace = ctx.durable_object("CHATROOM")?;
let stub = namespace.id_from_name("A")?.get_stub()?;
stub.fetch_with_str("/messages").await
})
.get("/secret", |_req, ctx| {
Response::ok(ctx.secret("CF_API_TOKEN")?.to_string())
}) …
```
> Simplify router args, and enable shared data throughout routes

- worker/src/response.rs
- worker/src/router.rs
This PR mostly adds sync and async router fns for the missing HTTP methods HEAD, PUT, PATCH, DELETE, OPTIONS, CONNECT and TRACE.
I originally added a `with_status_code` setter to `Response` in my fork, but later saw that you have since added a nearly identical method, so I merged the two commits and kept `with_status` as the name from the main branch (though perhaps `with_status_code` should be used to be consistent with the existing getter). Let me know if you would prefer to have a separate PR for the `with_status` return value type change.
> Add missing router methods

- worker-sandbox/src/lib.rs
- worker/src/response.rs
- worker/src/router.rs
Slight modification of #33, whereby some HTTP verb handler methods should be omitted due to platform restrictions. `TRACE` and `CONNECT` are not supported and the platform will not yield any control to the Worker for these. 
Also, I have changed the `with_status` implementation to return `Self` and skip the range check for valid HTTP spec status codes. While it is nice to check this at the Rust level, it hinders the usability of `with_status` (as it would likely be `map`'d from a `Response::from_json(...)` or something and thus requires the Result to be handled within the map. Unless I have something wrong here, which is completely possible :) 
I am going to merge this ASAP, and we can make further considerations for the `with_status` method. But merging this should unblock other PRs from …
> Match http handler methods to platform support

- worker-build/src/main.rs
While trying the Getting Started steps I had to locally fix these issues to continue because the latest Rust compiler reports errors on building worker-build. The fixes are simple and after making them I was able to successfully run the example, make changes to the worker and see those changes applied.
> Fix two compiler errors about iterating arrays and remove one unneeded unsafe block

- worker/src/response.rs
- worker/src/router.rs
Depends on #33 
I noticed that I could not add a catchall route `/*whatever` without causing a conflict with an existing route `/something`, even if the 2 routes used different HTTP methods. I am not sure whether this is expected behavior, but I thought that it might make sense to check conflicts only for routes with the same HTTP methods, which is what this PR implements.
For example, with this PR it is possible to define a `/*whatever` route for OPTIONS requests without causing conflicts with any existing and more specific GET route.
> Router avoid method conflicts

- worker-sandbox/src/lib.rs
- worker/src/router.rs
(I am honestly not totally sure whether this PR adds any value compared to a more specific `not_found` handler.)
I think of the `not_found` case as a kind of "fall-through" pattern in the pattern matching logic. The current implementation of `not_found` is specific to the 404 case, however, because it assumes a catchall route and always maps the response status to a 404. This is certainly the most common case for a fall-through route, so it might make sense to prioritize this situation, but perhaps it would be useful to generalize the logic and allow for arbitrary patterns? (One example I was thinking of is a "proxy router", which only handles a few specific methods and routes, but wants to pass on all other method + route combinations to a different router or even call another worker.) …
> Generalize `not_found` handler to handle arbitrary patterns

- worker-sandbox/src/lib.rs
- worker/src/response.rs
- worker/src/router.rs
This PR builds on #34, adding explicit route handler for non-match patterns using the `not_found` and `not_found_async` methods.
It also modifies the `worker-sandbox` Worker to narrow its match handlers to more specific HTTP methods to allow for better testing of wildcard patterns and `not_found` handler.
> Merge PR for #34, add or_else_any_method explicit handlers

- worker-sandbox/Cargo.toml
- worker-sandbox/src/lib.rs
- worker/src/router.rs
This PR removes the `Option` from the RouteContext and Router types containing the user provided data which is to be shared amongst routes. This was a leftover artifact from a previous design and doesn't provide any useful functionality, so it's be re-worked and removed. 
Additionally, the `ctx.data()` method which returns the Router data now returns a `&D`, so that we do not force any user to implement `Clone` on their type. If ownership of the data is required, users can implement `Clone` and call `.clone()` on their data within the route.
> remove Option container from router data, provide method to use no router data 

- worker-macros/src/durable_object.rs
- worker/src/request.rs
This PR adds support for mutating a path in-place for a `Request`s using `req.path_mut()`.
See https://github.com/cloudflare/workers-rs/issues/89 for more information.
> feat: support mutable Request paths

- worker-sandbox/src/lib.rs
- worker/src/router.rs
I specifically need this to call state.put in a durable object, I could also use a mutable getter, but there doesn't seem to be any reason why this field isn't public. It's just user supplied data after all, the framework doesn't have any expectations about how it can change. If for some reason a mutable getter (or something else) would be preferable, I'm happy to change this PR to do that instead.
I left the old getter in place for backwards compatibility, but with a deprecation warning, since using a getter when the field is directly available is unnecessary.
> refactor: Make data field of RouteContext public

- worker-sys/src/global.rs
- worker-sys/src/lib.rs
- worker/src/lib.rs
Maybe it's better to wrap them in a `console` mod, e.g., `console::error!`
> Add `console.debug`, `console.error` & `console.error`

- worker/src/response.rs
You can't actually obtain the "raw bytes" of a response body without this change.
> don't interpret raw bytes as text

- worker/src/response.rs
> fix: response body access converting body as string

- README.md
- worker-sandbox/src/lib.rs
- worker/Cargo.toml
Fixes #101. Version `0.5.0` contains breaking changes with the `get` operation on KV stores. These changes were made to fix inconsistencies with the JS api, but it unintentionally fixed this issue.
> chore: update worker-kv to 0.5.0

- worker/Cargo.toml
`chrono-tz` 0.4 does not disable the default features of `chrono` 0.4, which include the feature `oldtime` that depends on an obsolete version of the `time` crate that is vulnerable to [RUSTSEC-2020-0159](https://rustsec.org/advisories/RUSTSEC-2020-0159).
Besides, `chrono-tz` 0.4.1 [does not have any default features](https://github.com/chronotope/chrono-tz/blob/aa553ccc060404da7c65cfae1c136c949c6fbf1c/Cargo.toml) that can be disabled. Setting `default-features = false` on it does not have any effect.
> Bump chrono-tz to 0.6

- worker/src/formdata.rs
Fixes an issue where individual bytes were being passed to [File's constructor](https://developer.mozilla.org/en-US/docs/Web/API/File/File), where they'd be added to the file's content as a string. This effectively acted as this snippet:
```js
const bytes = new TextEncoder().encode("Hello");
const file = new File(bytes, "test");
const text = await file.text();
// Prints 'false'
console.log(text === "Hello");
// Prints 'true'
console.log(text === "72101108108111")
```
> Fix malformed data being used as file contents

- worker/src/formdata.rs
This will expose the size & type functions to match how you would use them natively in js/ts workers.
continue of #110 with changes requested.
> feat: add size and type methods to formdata

- worker-sys/src/response.rs
- worker/src/response.rs
Fixes issue where responses can have their bodies corrupted. This is caused by us giving JS the body's bytes as a reference to a byte slice, which is then dropped causing a use after free. Most of the time this is fine, but occasionally the allocator will allocate something that overlaps with the response body.
To fix this, we instead give the [Response constructor](https://developer.mozilla.org/en-US/docs/Web/API/Response/Response) an owned `Uint8Array` that doesn't have any references into the wasm memory.
Probably fixes #64 or at least parts of it.
> fix: responses occasionally corrupted

- .github/workflows/lint.yml
- worker-macros/Cargo.toml
- worker-sys/Cargo.toml
- worker/Cargo.toml
Enforces valid formatting and lints in an effort to close #58. Requires #119 to be merged before this PR.
This also temporarily pins wasm-bindgen to `0.2.78` because of rustwasm/wasm-bindgen#2774.
> Add linter github action

- worker-sys/src/response.rs
- worker/src/response.rs
I was also thinking about cloning the headers in the other `From` implementation:
```rust
impl From<EdgeResponse> for Response {
fn from(res: EdgeResponse) -> Self {
Self {
// CLONE HERE
headers: Headers(res.headers() /* .clone() */),
status_code: res.status(),
body: match res.body() {
Some(_) => ResponseBody::Stream(res),
None => ResponseBody::Empty,
},
}
}
}
```
A response coming from the `cache` will not have modifiable headers, but this might sometimes not be necessary, would help a lot with ergonomics though.
Edit: Forgot I opened an issue for that, this fixes #112
> fix: headers are not applied to stream response

- worker/src/router.rs
Hi,
since data just got updated to use direct field access instead, but env is facinig the same limitiations, I thought a PR to fix that would be a good idea.
> Direct field access for RouteContext#env

- worker/src/cors.rs
- worker/src/http.rs
- worker/src/lib.rs
- worker/src/response.rs
This PR is a pure QoL PR, which aims to make it easier to configure a CORS policy and apply it to responses using `with_cors` or `with_cors_unsafe` (for convenience).
> Extend the Response with_cors!

- worker-sandbox/src/lib.rs
- worker-sys/Cargo.toml
- worker-sys/src/lib.rs
- worker-sys/src/response.rs
- worker-sys/src/response_init.rs
- worker-sys/src/websocket.rs
- worker/src/lib.rs
- worker/src/response.rs
- worker/src/websocket.rs
My initial approach to supporting websockets in workers-rs.
Sending data works fine, though receiving data - for example through onmessage - does not work yet.
I'd appreciate some help figuring this out!
Also at maintainers, would this PR, if properly documented, get an OK from you?
> WebSocket support

- worker-macros/src/event.rs
Follow-up of #106 
```
error[E0433]: failed to resolve: use of undeclared type `Response`
--> cf-worker/src/lib.rs:45:1
|
45 | #[event(fetch, respond_with_errors)]
| ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ not found in this scope
|
= note: consider importing one of these items:
crate::Response
twitter_api::transport::Response
web_sys::Response
worker::Response
= note: this error originates in the attribute macro `event` (in Nightly builds, run with -Z macro-backtrace for more info)
```
> Fix unresolved type Response in macro generated code

- worker-sandbox/tests/util.rs
- worker-sys/src/file.rs
- worker-sys/src/request_init.rs
- worker-sys/src/response_init.rs
- worker/src/durable.rs
- worker/src/env.rs
- worker/src/headers.rs
- worker/src/request_init.rs
Cleans up some lints in the integration tests and removes any unnecessary `#[allow]`s that are no longer required. Makes no changes to the API except adding two `Default` implementations on `ListOptions` and `Headers`.
> Cleanup clippy lints

- worker/src/websocket.rs
It's a little cumbersome to get raw (binary) data out of the event, without this, so that's why!
> Utility Methods on MessageEvent

- worker/src/response.rs
Depending on the code path how the Response is constructed, the headers will eventually be immutable.
This PR fixes this by cloning the headers into a new object, applying the changes there and overwrites the old headers after.
> CORS Immutable Headers

- .github/workflows/test.yml
- Cargo.toml
- worker-build/Cargo.toml
- worker-build/bindgen-test-subject/Cargo.toml
- worker-build/bindgen-test-subject/src/lib.rs
- worker-build/src/main.rs
Previously we generated a `export_wasm.mjs` that imported all of the glue generated by wasm bindgen and modified the glue to import from the generated file. This caused a circular import leading to some functions, specifically ones that were just const aliases of builtins, generated by wasm-bindgen to be uninitialized and cause a crash. This bug can be replicated by making a worker that tries to use [Math::random()](https://docs.rs/js-sys/latest/js_sys/Math/fn.random.html).
To fix this we move all of the code in the `export_wasm.mjs` to that glue file. I don't think this would cause any side effects but I'd like to know what you think @nilslice.
> fix: uninitialized wasm imports

- worker-sandbox/Cargo.toml
- worker-sandbox/src/lib.rs
- worker-sandbox/tests/websocket.rs
- worker-sys/src/websocket.rs
- worker/Cargo.toml
- worker/src/websocket.rs
The current WebSocket api is closely modeled after the JavaScript WebSocket api which is functional but seems like a strange fit inside of a rust program. This PR is meant to refactor the WebSocket api to feel more *rust-y*.
Inspiration was taken from several other rust http frameworks (primarily [axum](https://docs.rs/axum/latest/axum/extract/ws/struct.WebSocket.html) and [warp](https://docs.rs/warp/latest/warp/filters/ws/struct.WebSocket.html)) but some of the restrictions JavaScript places on us requires us to make some changes. The biggest different in my opinion is that we don't use a [Sink](https://docs.rs/futures/latest/futures/prelude/trait.Sink.html) for sending messages through the WebSocket, which is because [send](https://developer.mozilla.org/en-US/docs/Web/API/WebSocket/send) …
> refactor websockets to be more idiomatic

- .github/workflows/lint.yml
- worker-sandbox/tests/websocket.rs
With the addition of integration testing for WebSockets we unintentionally introduced a warning where some functions declared in the integration test's util module were unused. This is because all integration tests are compiled as separate binaries so for the websocket binary functions weren't used for that specific compile job.
This also adjust flags in the CI to catch warnings like this in the future.
> chore: fix unused function warning

- worker/src/request_init.rs
hi y'all, just a fix for what is presumably a copy/paste error: `cache_key` is a string not a bool.
> fix type of CfProperties.cache_key

- Cargo.lock
- worker-build/Cargo.toml
- worker-build/bindgen-test-subject/src/lib.rs
- worker-build/src/bundler.rs
- worker-build/src/main.rs
Adds support for `wasm-bindgen`'s [snippet](https://rustwasm.github.io/wasm-bindgen/reference/js-snippets.html) feature by moving the snippets into the correct directory and then bundling them with [SWC](https://github.com/swc-project/swc).
This PR doesn't strictly require the SWC bundler step, instead of bundling we can rename all of the generated snippets and transform the javascript. But I believe that bundling is the preferred route as it opens up the possibility for us to build bindings around existing JavaScript libraries that aren't in the global scope if we were to allow the bundling of `node_modules` noted [here](https://github.com/cloudflare/workers-rs/commit/417083fa71306df66838576af56b8eaf9b0c6b3b#diff-72e505a9360efda6be70299bfcddfafd00f301b7ed8bae515c5316d25e78b4bbR89). …
> Support for JavaScript snippets

- worker-build/src/main.rs
- worker-macros/src/event.rs
- worker-sandbox/src/lib.rs
- worker-sandbox/tests/requests.rs
Adds support for a `start` event that is invoked when the worker is initialized. This is useful for things like setting panic hooks, setting up loggers, creating any initial state, etc.
Under the hood this uses wasm-bindgen's [start feature](https://rustwasm.github.io/docs/wasm-bindgen/reference/attributes/on-rust-exports/start.html) and because of that we inherit it's limitations, like not being able to register multiple start events.
> Start event

- Cargo.lock
- worker-build/Cargo.toml
- worker-build/bindgen-test-subject/Cargo.toml
- worker-macros/Cargo.toml
- worker-sys/Cargo.toml
- worker/Cargo.toml
The constraint `wasm-bindgen = "=0.2.78"` make using wasm-bindgen with some other packages impossible. Perhaps, we could relax that constraint?
> Bump wasm-bindgen and loose the version constraint

- Cargo.lock
- worker-build/Cargo.toml
- worker-build/bindgen-test-subject/Cargo.toml
- worker-macros/Cargo.toml
- worker-sandbox/Cargo.toml
- worker-sandbox/src/lib.rs
- worker-sys/Cargo.toml
- worker-sys/src/lib.rs
- worker/Cargo.toml
Updates dependencies, notably `wasm-bindgen` which we were pinned on to avoid giving dependents linting warnings.
> chore: update dependencies

- worker/src/response.rs
This gives users more power to perform low level operations on a response.
> Allow to access the response body

- worker-sandbox/src/lib.rs
- worker-sandbox/tests/requests.rs
- worker/src/response.rs
Adds the ability to clone [Response](https://docs.rs/worker/latest/worker/struct.Response.html)s. As a part of this commit we also refactor [ResponseBody](https://docs.rs/worker/latest/worker/enum.ResponseBody.html) to not include a whole request as part of the [Stream](https://docs.rs/worker/latest/worker/enum.ResponseBody.html#variant.Stream) variant. This is a breaking change, but makes a lot more sense.
> feat: add cloned to Response

- README.md
This is a patch to fix the getting started portion of the `README.md` to use [Wrangler 2.0](https://github.com/cloudflare/wrangler2).
This is a temporary fix until we update all the documentations.
> Fix `README.md` to use wrangler 2 instead of wrangler 1

- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/ISSUE_TEMPLATE/feature_request.yml
Adds Github templates for reporting bugs and requesting features.
Bug report form looks like the following:
Feature request form looks like the following:
> Add Github templates for bug reports and feature requests

- Cargo.lock
- worker-sandbox/Cargo.toml
- worker-sandbox/src/lib.rs
- worker-sandbox/tests/requests.rs
As a continuation of the work in #188, it occurred to me that I actually forgot to work on `worker-sandbox`. Thus, I have not _actually_ removed the `futures` crate from `Cargo.lock` _yet_. This PR resolves this issue.
Thanks! 🎉
> Deps: remove usage of full `futures` in `worker-sandbox`

- worker/src/request.rs
Thought I'd do a try of #179 
`Url` is actually a foreign type, so a trait is required to extend its functionality, unless this is sent upstream instead. 
Because a query may have multiple values for a key, the function returns an iterator. For assumed-unique parameters, perhaps a
```rust
fn first_value_of(&self, key: &str) -> Option<Cow<'a, str>>
```
function might also be useful.
> Method for easily getting query parameters

- worker/src/lib.rs
Previously these could be obtained via return types but the the actual type was not exported by the crate, making it impossible to use in a case where you need static typing.
Fixes #192
> fix: export Var and Secret

- Cargo.lock
- worker-build/src/install.rs
- worker-macros/src/durable_object.rs
- worker-sandbox/src/alarm.rs
- worker-sandbox/src/counter.rs
- worker-sandbox/src/lib.rs
- worker-sandbox/tests/requests.rs
- worker-sandbox/wrangler.toml
- worker-sys/src/cache.rs
- worker-sys/src/durable_object.rs
- worker/Cargo.toml
- worker/src/durable.rs
- worker/src/request.rs
- worker/src/request_init.rs
This PR implements the DO Alarm API based off of the signatures found in the [storage docs](https://developers.cloudflare.com/workers/runtime-apis/durable-objects/#methods).
I think there's a bug in the way I've implemented the binding for `getAlarm`. When an alarm does not exist, I expect `getAlarm` to return `null` and in rust `Ok(None)`, however I seem to be getting an error instead. When the alarm does exist (`set_alarm` immediately followed by a `get_alarm`) I get the expected output.
I haven't been able to test that the alarm does trigger, however everything compiles and it looks like the generated shim has the required methods. I'll be testing later tonight.
Also, I have `set_alarm` take in a `DateTime<Utc>` whereas `get_alarm` returns an `i64`. 
* Thoughts on having both a …
> Add DO Alarm API

- worker-build/src/main.rs
esbuild bundle should be minified by default. If this behavior is not desired you may use the environment variable `NO_MINIFY`.
Closes #210
> feat(esbuild): minify esbuild bundle by default

- worker-build/src/install.rs
- worker-build/src/main.rs
- worker-sandbox/remote-service/package.json
- worker-sandbox/remote-service/service.js
- worker-sandbox/remote-service/wrangler.toml
- worker-sandbox/src/lib.rs
- worker-sandbox/tests/requests.rs
- worker-sandbox/wrangler.toml
- worker/src/env.rs
- worker/src/fetcher.rs
- worker/src/router.rs
Adds support for service bindings by re-using the `Fetcher` implemented in #218.
> Add service binding support

- worker-sys/src/cf.rs
- worker/src/cf.rs
Makes the `isEUCountry` binding available in Rust.
Docs: https://developers.cloudflare.com/workers/runtime-apis/request/#incomingrequestcfproperties
See also: https://github.com/cloudflare/workers-types/pull/245 for the TypeScript analogue.
> Add support for isEUCountry binding

- worker/src/cf.rs
Fixes #265 by adding a new `timezone_name` property to `Cf` in order to avoid a breaking change to `timezone`.
> Add `timezone_name` to `Cf` properties

- worker/src/request.rs
Fixes #263 by setting `immutable` to false when a `Request` is cloned, bringing it in line with the JS implementation.
> Allow cloned Requests to be mutable

- worker-build/src/main.rs
- worker-sandbox/src/lib.rs
- worker-sandbox/src/test/export_durable_object.rs
- worker-sandbox/tests/requests.rs
- worker/src/cors.rs
- worker/src/env.rs
- worker/src/error.rs
- worker/src/headers.rs
- worker/src/request.rs
Recently clippy added a lint requiring the new format syntax, causing all CI runs to fail.
> chore: fix new clippy lints

- worker-sandbox/src/lib.rs
- worker-sandbox/src/r2.rs
- worker-sys/src/r2.rs
- worker/src/r2/builder.rs
- worker/src/r2/mod.rs
This extends the [recently implemented R2 bindings](https://github.com/cloudflare/workers-rs/pull/215) with support for [multipart upload](https://developers.cloudflare.com/r2/data-access/workers-api/workers-api-reference/#r2multipartupload-definition).
> Add support for multipart uploads to the R2 bindings

- Cargo.lock
- worker-build/src/main.rs
- worker-macros/Cargo.toml
- worker-sys/Cargo.toml
- worker/Cargo.toml
`wasm-bindgen` seem to have altered their WASM import format (see https://github.com/rustwasm/wasm-bindgen/pull/3152), meaning the `use_glue_import` function in `worker-build` no longer correctly replaced the import.
Fixes https://github.com/cloudflare/workers-rs/issues/276
> Correct bindgen glue import in worker-build

- README.md
Rather than hardcode a value for the limit (which may change, and there are different limits for free vs. paid plans), link directly to the docs page where Workers limits are explained and kept up-to-date.
> Link to Worker size limits

- README.md
Looks like the templates repository is no longer used and templates have been moved.
Just stumbled over this when looking up the template.
> Use new template link

- worker/src/lib.rs
Plumb the TLS client certificate information through the API. This is currently possible via `req.cf().tls_client_auth()`, but it is useful to be to reference the `TlsClinetAuth` structure itself in struct/enum definitions.
> Expose `TlsClientAuth` struct in the public API

- worker-sys/src/types/durable_object/state.rs
- worker/src/durable.rs
This is needed to get the usual `waitUntil` behaviour for DO.
In JS you can just "fire and forget" the promise and DO will take care of ensuring it runs: https://developers.cloudflare.com/workers/runtime-apis/durable-objects/#durable-object-class-definition
But as futures are lazy in Rust, this is the only way.
Related: https://github.com/cloudflare/workers-rs/issues/151
> Exposes wait_until method on Durable Object state

- worker-sandbox/src/r2.rs
- worker-sandbox/tests/requests.rs
- worker/src/env.rs
Exposes `get_binding` for accessing bindings that do not have a type in workers-rs.
> chore: expose get_binding for env

- worker/src/lib.rs
The `worker::cache::CacheKey` is useful when the user wants to wrap the cache methods by accepting the same bounds for the generic key type.
The `worker::env::EnvBinding` export is a follow-up to https://github.com/cloudflare/workers-rs/pull/318. Without that export, the user cannot implement the `EnvBinding` trait which is required by the the `worker::env::Env::get_binding()` method.
> Export worker::cache::CacheKey and worker::env::EnvBinding

- Cargo.lock
- Cargo.toml
- worker-build/src/js/shim.js
- worker-build/src/main.rs
- worker-sys/src/types.rs
- worker-sys/src/types/socket.rs
- worker/Cargo.toml
- worker/src/error.rs
- worker/src/lib.rs
- worker/src/socket.rs
> Outbound TCP Sockets

- Cargo.lock
- worker-build/Cargo.toml
- worker-build/src/main.rs
- worker-macros/Cargo.toml
- worker-macros/src/durable_object.rs
- worker-sandbox/Cargo.toml
- worker-sys/Cargo.toml
- worker/Cargo.toml
Bumps dependencies, notably `syn` and `wasm-bindgen` as well as fixing breaking changes with the generated JS and syn's item renames.
> Bump cargo dependencies

- package-lock.json
- package.json
- worker-sandbox/src/lib.rs
- worker-sandbox/src/test/export_durable_object.rs
- worker-sandbox/src/test/mod.rs
- worker-sandbox/src/test/put_raw.rs
- worker-sandbox/tests/durable.spec.ts
- worker-sandbox/tests/mf.ts
- worker-sandbox/wrangler.toml
- worker/src/durable.rs
The current `put_multiple` method forces the caller to use a predefined struct
which means a user of the lib can't store multiple runtime defined keys at once.
Having a `_raw` methods let's the caller construct their own object at runtime
to pass in.
> Add Storage::put_multiple_raw method to allow for runtime defined kv pairs to be stored

- worker-build/src/main.rs
The `COREDUMP_FLAGS` environment variable allows to pass cli flags to the wasm-coredump-rewriter executable, in the form:
```
COREDUMP=1 COREDUMP_FLAGS="--check-memory-operations --abcd" worker-build --dev
```
> Allow to pass wasm-coredump-rewriter cli flags

- README.md
- worker-sandbox/src/lib.rs
- worker/src/request.rs
This is in response to issue #353 
I understand that this change is technically a breaking change. Another option is to silently add the `cf` field to any requests constructed. There are situations, like for the mail events, where there is no request to copy from. 
Bearing this all in mind, the `cf` field _is_ wrapped in `Option` on the request struct, and therefore having the `cf()` method also return an `Option` would make sense. 
There're more details in the linked issue (in the workerd repo), but the issue can be seen for example in an upstream TS service calls a bound rust worker. Something like:
```typescript
let new_request = new Request("https://foo.com", { method: "POST", body: request.body })
```
Here a new request is being made, but the `cf` property is not being copied over. …
> Make `cf()` return an option

- Cargo.lock
- examples/tokio-postgres/Cargo.toml
- examples/tokio-postgres/src/lib.rs
- worker/Cargo.toml
- worker/src/socket.rs
This has been tested and works but the API added to `tokio-postgres` is hacky and will need some refinement. 
Closes #386
> Postgres TLS Support

- README.md
We (@kodadot) are huge fans of Cloudflare and Workers and we have a ton of workers in the prod (Rust / TS).
As anyone would upgrade to latest version they would meet this very scary error 
```
[INFO]: 🌀  Compiling to Wasm...
Compiling proc-macro2 v1.0.67
Compiling phf_shared v0.11.1
Compiling serde v1.0.164
Compiling syn v1.0.109
Compiling unicode-normalization v0.1.22
Compiling mio v0.8.8
Compiling matchit v0.4.6
error[E0432]: unresolved import `crate::sys::IoSourceState`
```
The only mention I found was in Cloudlfare's discord
> :memo: caveat when upgrading to worker 0.0.18

- worker/src/formdata.rs
This PR creates a helper method for `FormData` so that users don't have to pattern match for `FormEntry::Field` every time they want to use this. 99% of the time the passed arguments aren't files.
> add get_field helper method

- worker/src/durable.rs
Fix a syntax error (missing comma) and a lint warning, and remove a blank line.
This is part of the [public documentation](https://docs.rs/worker/0.0.18/worker/durable/trait.DurableObject.html#example); might as well have it be correct and idiomatic.
> fix docs typos in `DurableObject`

- worker/src/request_init.rs
Fixes #442
Serializes `ttl_status_map` as an object instead of a JavaScript Map using a serde_wasm_bindgen serializer.
Inspecting cf properties, TTL attributes are now present.
Before:
```Rust
request cf properties: Cf { inner: IncomingRequestCfProperties { obj: Object { obj: JsValue(Object({"apps":true,"cacheEverything":true,"cacheKey":"","cacheTtl":0,"cacheTtlByStatus":{},"minify":{"__wbg_ptr":1455240},"mirage":true,"polish":"off","resolveOverride":"","scrapeShield":true})) } } }
```
After
```Rust
request cf properties: Cf { inner: IncomingRequestCfProperties { obj: Object { obj: JsValue(Object({"apps":true,"cacheEverything":true,"cacheKey":"","cacheTtl":0,"cacheTtlByStatus":{"200-299":5,"300-399":10},"minify":{"__wbg_ptr":1311768},"mirage":true,"polish":"off","resolveOverride":"","scrap …
```
> Serialize cache_ttl_by_status as object in cf properties

- Cargo.lock
- worker-macros/Cargo.toml
- worker-sandbox/Cargo.toml
- worker-sandbox/src/lib.rs
- worker-sandbox/tests/request.spec.ts
- worker-sys/Cargo.toml
- worker/Cargo.toml
- worker/src/router.rs
Looks like `matchit` made some pretty substantial changes to params parsing behavior, so need to make this clear in release notes. 
* https://github.com/ibraheemdev/matchit/releases
> Update all dependencies

- .gitignore
- worker/src/websocket.rs
I found myself needing to set the protocol when creating a websocket client. This exposes a new function that allows the caller to the protocol.
Pretty straightforward, happy to adjust as needed!
> add the ability to set the protocol(s) when creating a websocket client

- examples/hyper/src/lib.rs
- worker/src/response.rs
```rust
Response::from_html("<h1>Hello, World! 🐱</h1>")
```
> Make Response::from_html use `text/html; charset=utf-8`

- README.md
The current install instructions do not work. The best path is to manually get the example repo and install dependencies from there.
Addresses https://github.com/cloudflare/workers-sdk/issues/3348
> docs: remove wrangler init reference in readme.

- worker/src/r2/mod.rs
This commit adds a new function to `r2::ObjectBody` to allow the underlying `ReadableStream` for the body of an R2 object to be used to create a `ResponseBody`, via the `ResponseBody::Stream` variant.
This adds support for cases where workers can hand a reference to the R2 object to the workers runtime for streaming to the client, unmodified. Importantly, this allows the worker to avoid CPU usage while streaming the object.
Before this commit, `ObjectBody::Stream` could be used but that would result in unexpected CPU usage during the streaming process leading to the working hitting the CPU limit for large (> 150 MB) R2 objects.
Closes #389
> Add `response_body` function to `r2::ObjectBody`.

- worker-sys/src/types/r2.rs
- worker-sys/src/types/r2/checksums.rs
- worker-sys/src/types/r2/object.rs
- worker/src/r2/builder.rs
- worker/src/r2/mod.rs
Apparently its working fine, I only tested with my production use cases and it seemed ok.
I haven't done any testing, as I do my tests using wasm-bindgen-test, I have something like 600 on a single crate.
I talked with the wasm-bindgen-test folks and they would like to support workerd...
Then I talked to MrBot about this and he said it seemed doable once he gets the vitest miniflare 3 support back as it was on 2.
Are workers-rs tests going to return to wasm-bindgen-test or continue on vitest?
> Added support for R2 Checksums to GET and PUT.

- Cargo.lock
- package.json
- worker-sandbox/Cargo.toml
- worker-sandbox/src/d1.rs
- worker-sandbox/src/lib.rs
- worker-sandbox/tests/d1.spec.ts
- worker-sandbox/tests/mf.ts
- worker-sandbox/tests/request.spec.ts
- worker-sandbox/tests/subrequest.spec.ts
- worker-sys/src/types/incoming_request_cf_properties.rs
- worker/src/body/body.rs
- worker/src/cf.rs
- worker/src/durable.rs
- worker/src/env.rs
- worker/src/fetch.rs
- worker/src/fetcher.rs
- worker/src/headers.rs
- worker/src/http/request.rs
- worker/src/lib.rs
- worker/src/queue.rs
- worker/src/request_init.rs
The tests are all running now, even d1, that now run perfectly on miniflare.
I tried to be as minimal as possible, but I had to port some things from the latest version.
I wasn't sure what was going to be the final API after the final merge, so I tried to minimize impact on rebase or merge.
You asked for the tests, I used your PR 440 as reference, but I couldn't PR to it.
Please tell me how can I help to make things as smooth as possible.
Thanks!
> Added remaining routes and fixed testes

- Cargo.lock
- Cargo.toml
- worker-build/Cargo.toml
- worker-macros/Cargo.toml
- worker-sandbox/Cargo.toml
- worker-sys/Cargo.toml
- worker/Cargo.toml
Notes:
- related/created from https://github.com/cloudflare/workers-rs/issues/433
- updating depencencies/using workspace dependencies
> update/use workspace dependencies (wasm_bindgen, etc)

- worker/src/queue.rs
I'm in the process of migrating a worker to use `axum` and this missing impl prevents using `Queue` in a state that can be attached to a router. Another issue is a missing `Send`/`Sync` impl on `KvStore` but that lives in the `worker-kv` repo, outside of the cloudflare org. Should I make a PR there as well?
> impl Send/Sync for Queue

- worker-sys/src/types/durable_object/state.rs
- worker/src/durable.rs
get_tags allows a durable object to read metadata describing the websocket.
It's useful when a durable object is managing multiple websockets and needs to discover which one sent a message that caused a hibernating websocket to wake.
> implement get_tags for hibernatable websockets

- worker/src/queue.rs
I think there is no reason not to have this. It will come in handy when the https://github.com/cloudflare/workers-rs/pull/477 lands because `axum` requires state to implement `Clone`.
> Derive Clone for Queue

- worker-sandbox/src/d1.rs
- worker-sandbox/tests/d1.spec.ts
- worker-sandbox/tests/mf.ts
- worker/src/d1/mod.rs
`bind` does not actually need owned values
> Introduce D1PreparedStatement.bind_refs which does not take ownership

- worker/src/env.rs
#482
Inlined the documentation so it is copied over from the private module.
> Fix absence of worker::secret documentation

- README.md
The current code snippet is inverting the parts that should be marked as code; this fixes that issue.
> README: Fix beginning of code snippet

- worker-sys/src/types/fetcher.rs
- worker/src/fetcher.rs
Continuing the game of whack-a-type...
I implemented `Send` and `Sync` for the `worker-sys` type. I can change that to the wrapper in `worker` if you think that makes more sense.
> Implement Send, Sync and Clone for Fetcher

- .github/workflows/create-release-pr.yml
Adds [cargo-semver-checks](https://crates.io/crates/cargo-semver-checks) when creating a new release. Since we are still on `0.x.y`, these checks do not detect anything by default. I have forced the checker to treat every release as a `minor` version so that it will highlight any breaking changes. 
Since we still want to be able to ship breaking changes occasionally, I have set these steps to not fail the build, and instead will review them manually. 
I've also added a sanity check build step to make sure there are no issues introduced by `cargo update`. Ideally the full test suite would still run on the PR, but I will have to figure out how to do that later.
> Add semver checks and sanity-check build to create-release-pr

- examples/kv/Cargo.toml
- worker-kv/Cargo.toml
In most cases `worker-kv` will not change so we shouldn't release it on every release PR.
> Don't increment KV version when creating release PR

- .github/workflows/create-release-pr.yml
- .github/workflows/pullrequest.yml
Not very well documented, but looks like `binstall` will automatically detect `GITHUB_TOKEN` environment variable which allows fetching GitHub release artifacts without encountering rate limits. 
https://github.com/cargo-bins/cargo-binstall/blob/8de3ec8fb72df0f5052768e750a70ebceafbbe3e/crates/bin/src/args.rs#L302
> Supply token so that cargo-binstall does not encounter rate limits

- worker-sys/src/types/socket.rs
- worker/src/socket.rs
#441 
I'm a bit confused regarding the actual implementation of Socket.opened itself. I created all the necessary bindings, same as the ones [already implemented](https://developers.cloudflare.com/workers/runtime-apis/tcp-sockets/#Socket), but I'm not sure if I'm done. The `Socket` struct confuses me. I know the `inner` is the bound JS object itself, and the rest are mostly streams and options. What do Options such as `close` do? They are used in Tokio traits such as `AsyncWrite`. It looks like to me that particular one returns whether the Socket has closed yet, and the implementation also indicates that.  I tried to decipher what I think is the [original implementation](https://github.com/cloudflare/workerd/blob/main/src/workerd/api/sockets.h) of `opened` but have not been successful in …
> Add Socket.opened implementation

- worker/src/d1/mod.rs
Example usages to debug in application code:
```rust
let res = get_d1(env)?
.prepare("SELECT count(*) FROM accounts WHERE email = ?1")
.bind(&[email.into()])?
.raw_js_value()
.await?;
console_log!("debugging via raw_js_value: {:?}", res);
let promise = get_d1(env)?
.prepare("SELECT count(*) FROM accounts WHERE email = ?1")
.bind(&[email.into()])?
.inner()
.first(None);
let res = JsFuture::from(promise).await?;
console_log!("debugging via inner: {:?}", res);
```
> Expose D1 Statements JsValue API

- worker/src/d1/mod.rs
very small improvement...
on the JS side it already knows the capacity of the Vec 
so `to_vec()` may be slightly more efficient than iterating/collecting
> d1 js array optimization

- worker-macros/src/event.rs
This PR returns a generic 500 response to the client, instead of panicking, when an error is returned to the fetch handler. IMO panicking defeats the purpose of Rust's error handling model and propagating errors.
The `respond_with_errors` option avoids a panic but blindly returns the error to the client which is not good practice.
I can also add a new option if you want to keep the existing behavior. Or add a new panic option in case some people really want to do a panic.
> Return 500 instead of panicking when returning error to fetch handler

- examples/axum/Cargo.lock
- examples/axum/Cargo.toml
- worker-sandbox/Cargo.toml
- worker/Cargo.toml
Only depend on `axum` and provide utilities if needed.
> Introduce `axum` feature

- worker/src/http/response.rs
`worker` did not build with only `http` feature because `From<worker::Response>` for `http::Response<axum::Body>` was gated behind `http` feature instead of `axum` feature.
> Fix `axum` feature

- worker/src/r2/mod.rs
While trying to implement https://developers.cloudflare.com/r2/api/workers/workers-multipart-usage/ in Rust it appears that `uploadId` isn't exposed in the existing APIs. This PR rectifies that.
> 💡 Expose `uploadId` for multipart uploads

- worker/src/r2/mod.rs
Sits on top of #547 
Better diff: 87098013e96f009b90e5667f66c30865176539e0
Currently `Data` only exposes `FixedLengthStream`, however the node.js also allows the `ReadableStream` to be the argument to `put`.
https://github.com/cloudflare/workers-sdk/blob/ad1d056cb2710b790ff5d4532e9f694e099c27e2/packages/wrangler/src/r2/helpers.ts#L156
This adds the ability for `put` and `upload_part` to forward the `ReadableStream` from the `Request` body directly by just passing `req.inner().body().unwrap()`.
>  🎏 Add ReadableStream to Data 

- examples/custom-req/src/lib.rs
- worker-macros/src/event.rs
- worker-macros/src/lib.rs
- worker/src/request.rs
- worker/src/response.rs
This allows the `fetch` handler to return any error type that implements `std::error::Error`. This will allow the user to choose how they want to handle errors (use `worker::Error`, `anyhow`, `thiserror`, etc.). 
This also changes some behavior slightly:
1. If `respond_with_error` is enabled, this now uses `Display` to stringify the error instead of `to_string`. 
2. The error logged is now stringified with `Debug` and with `console_error` instead of `console_log`. 
cc @avsaase
> Allow returning any error that implements `std::error::Error`

- worker/src/r2/mod.rs
Fixes #316
Objective here was to provide an easy way to create an `UploadedPart` -- currently in my worker code I'm deserializing a custom object into a `part_number` and an `etag`, which I then use to construct the `UploadedPart` to be passed to `MultipartUpload::complete`
> feat: Allow instantiating an UploadPart from its constituent parts

- worker/Cargo.toml
The `worker` crate makes use of `impl Trait` in trait method return types now, but the error that old Rust versions output can be a little confusing.
```rs
error[E0562]: `impl Trait` only allowed in function and inherent method return types, not in trait method return types
--> worker\src\request.rs:312:36
|
312 |     ) -> std::result::Result<Self, impl Into<Box<dyn std::error::Error>>>;
|                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
|
= note: see issue #91611 <https://github.com/rust-lang/rust/issues/91611> for more information
```
[`rust-version`](https://doc.rust-lang.org/cargo/reference/manifest.html#the-rust-version-field) will instead output this:
``error: package `worker v0.2.0 (path)` cannot be built because it requires rustc 1.75 or newer, while the …
> Add MSRV to `worker` crate

- worker-sys/src/types/r2/range.rs
- worker/src/r2/builder.rs
Closes #560
Waiting for guidance on the behavior of `limit` without `offset`. For now I'd like to continue to match the JavaScript behavior.
> Use u64 for R2 range requests

- worker-sandbox/src/cache.rs
- worker-sandbox/src/counter.rs
- worker-sandbox/src/fetch.rs
- worker-sandbox/src/request.rs
- worker-sandbox/src/router.rs
- worker-sandbox/tests/clone.spec.ts
- worker-sys/src/ext/response.rs
- worker-sys/src/ext/response_init.rs
- worker/src/cf.rs
- worker/src/http/response.rs
- worker/src/lib.rs
- worker/src/response.rs
This expands `ResponseInit` to support all of the options available in JavaScript. Additionally, the builder pattern is adopted so that users do not have to specify all of these new fields as we add them (breaking change). There are a few questions I want to answer before merging this. 
Closes #567
> Add `encodeBody` and `cf` to ResponseInit. Adopt builder pattern.

- examples/tokio-postgres/src/lib.rs
`query` and prepared statements are now supported if caching is enabled
> Switch Hyperdrive example to  with note

- worker/src/lib.rs
This allows users to pass around the instance of `Hyperdrive`.
> Expose `Hyperdrive` from the worker crate

- worker/src/d1/mod.rs
Thanks to the official staff for reviewing. This PR is based on #337 .
When I tried to use `sea-orm` proxy connection, I found that the `D1Result` object could not obtain other information except data, so I traced the source code.
In fact, `worker-sys` has already declared the `meta` function, but `D1Result` under `worker` did not further extract and serialize this part of data. I made some simple work that `D1Result` can obtain this part of the content.
[Demo is here](https://github.com/langyo/cloudflare_worker_rust_demo).
> Add a binding to meta object for `D1Result`.

- worker-sys/src/types/tls_client_auth.rs
- worker/src/cf.rs
This adds support for getting a client's sha256 fingerprint.
> Support sha256 cert fingerprints in TlsClientAuth

- README.md
- worker-sys/src/types.rs
- worker-sys/src/types/version.rs
- worker/src/lib.rs
- worker/src/version.rs
Allows users to fetch the version metadata fron the worker environment. This is useful when using Gradual Deployments.
> Add support for Version Metadata Binding

- worker-sys/src/types/r2/object.rs
- worker/src/r2/mod.rs
This makes `Object::size()` return `u64`, in case the R2 object is larger than 2^32 bits.
Tested using an object that was smaller than 2^32 that the type conversion was successful.
> Make R2 Object::size return u64

- worker/src/router.rs
This PR relaxes the type of the callback
> `func: fn(Request, RouteContext<D>) -> T`
into
> `func: impl Fn(Request, RouteContext<D>) -> T + 'static`
which is an argument-position impl trait type (APIT), since I don't see any reason for requiring the passed-in callback is a function pointer, since we're immediately boxing it up and erasing the type.
Specifically, this ensures that you can pass a (currently nightly-only) async closure (`async ||`), which currently does *not* support being coerced to a fn ptr type. I'd like to avoid needing to implement that functionality that if possible.
> Relax type of callback arguments to Router methods

- worker/src/cors.rs
Small fix: I just noticed that the parameters should be named `headers` instead of `origins`.
> Fix typos in CORS argument names

- worker/src/formdata.rs
This allows FormData to be constructed and passed as JsValue later on. For instance, `RequestInit::new().with_body(formdata.into())`.
> [worker] Add FormData conversion into JsValue

- worker-build/src/js/shim.js
- worker-build/src/main.rs
When a client disconnects, code is not run to clean up `wasm-bindgen`'s "heap", and thus objects associated with the request leak. `wasm-bindgen` suggests the use of `FinalizationRegistry`, which we do not currently support due to security reasons. 
This change allows user's to specify `RUN_TO_COMPLETION` environment variable when running `worker-build`, which tricks the Workers runtime into executing the Promise that resolves the Response in a `waitUntil` context, even if the client disconnects. This should be used with caution, as your code may have side effects that you would not want to run if the client disconnects. 
Below is a graph of Wasm heap usage over time during a load test, first with existing behavior, and second with `RUN_TO_COMPLETION` enabled.
> Optionally run Response Promise to completion in waitUntil context

- Cargo.lock
- worker-build/Cargo.toml
Bumps `worker-build` for a release since it doesn't seem to be covered by the existing release workflow, which i checked by running `cargo release version patch`.
> chore: bump worker-build

- worker-build/src/js/glue.js
- worker-build/src/js/shim.js
- worker-build/src/main.rs
- worker-sandbox/wrangler.toml
- worker/src/router.rs
- worker/src/websocket.rs
Fixes #668 
1. When reference types are enabled, which is the default in Rust 1.82, `wasm-bindgen` will generate JS where some wasm imports that were previously functions get generated as variables due to the difference in the JS/wasm interop barrier. After we bundled with esbuild we ran into the issue where a wasm import was defined after the instance was initialized, which wasn't a problem for the pre-reference type builds since functions get automatically hoisted in JS.
2. Previously we weren't calling `wasm-bindgen`'s `__wbindgen_start` function but instead called our `start` function for any function with `#[event(start)]`, but when reference types are enabled this function setups the externref table. This was causing us to change the value in the externref table for the `UNDEFINED` …
> fix: support for externref

- worker-sandbox/src/assets.rs
- worker-sandbox/src/lib.rs
- worker-sandbox/src/router.rs
- worker-sandbox/wrangler.toml
- worker/src/env.rs
closes #644 
I went down a rabbit hole creating an entire new `Assets` env binding just to find out it's a `Fetcher`. In fact, you can use assets without this PR by just calling `env.get_binding::<Fetcher>("ASSETS")`.
Testing:
- Run `npx wrangler dev` in `worker-sandbox`
- Go to `/asset/test.txt`
- See `TEST` in browser
- Go to `/asset/doesnotexist.txt`
- See 404
> Workers Assets Binding

- worker-build/src/main.rs
This allows for users to provide their own JS shim and allowing them to customize behaviour: panic handling, wasm coredumps, and so on...
It defaults to the embedded shim in the binary to avoid breaking changes.
> Make `worker-build` support custom JS shims

- README.md
I'd mistakenly assumed when first reading this warning that I couldn't use anything from `tokio` (even through the existing text does just say the tokio async runtime).  Add a note to make it clear that runtime-agnostic tokio crates are still usable.
> Add note to readme about runtime-agnostic primitives from tokio

- Cargo.lock
- worker-macros/src/durable_object.rs
- worker-sandbox/Cargo.toml
- worker-sandbox/src/alarm.rs
- worker-sandbox/src/counter.rs
- worker-sandbox/src/test/export_durable_object.rs
- worker-sandbox/src/test/put_raw.rs
- worker-sandbox/tests/durable.spec.ts
- worker-sandbox/tests/mf.ts
- worker-sandbox/wrangler.toml
- worker/src/durable.rs
- worker/src/formdata.rs
- worker/src/headers.rs
- worker/src/response.rs
This updates to `&self` over `&mut self` references where possible, as a breaking alternative to https://github.com/cloudflare/workers-rs/pull/737.
This then correctly allows concurrent calls to methods, while retaining safe Rust semantics.
Durable object code will need to be updated to work with this new implementation shape - in particular using standard Rust cell idioms to protect mutable data fields on the durable object.
> Breaking Change: Use non-mutable methods for DurableObject, FormData, Headers & Response

- worker/src/durable.rs
Currently, [`durable::Storage::transaction`](https://docs.rs/worker/0.5.0/worker/durable/struct.Storage.html#method.transaction) requires that its closure implement `Copy`. This is way too strong a requirement, since you can't even do things like:
```rust
let key: String = get_dur_obj_key();
storage.transaction(move |tx| async move {
let val = tx.get(&key).await?;
});
```
The compiler yells, saying `the trait bound String: std::marker::Copy is not satisfied in {closure@...}`.
Fortunately, there's no inherent reason why this closure needs to implement `Copy`. This PR changes the transaction semantics to make use of `wasm_bindgen`'s built-in `FnOnce` support for futures.
> Remove unnecessary Copy constraint on `durable::Storage::transaction()`

- README.md
- worker-macros/src/durable_object.rs
- worker-sandbox/src/test/auto_response.rs
- worker-sandbox/src/test/export_durable_object.rs
As a follow-on to https://github.com/cloudflare/workers-rs/commit/f21e19ea4e92acc2ed15a5f0cceb51c109909af4 this automatically brings the `DurableObject` trait into scope when using the `durable_object` macro.
> feat: auto-import DurableObject when using durable_object macro

- worker/src/env.rs
this may be common, or may not, future refcasting should probably use the [ref-cast](https://docs.rs/ref-cast/latest/ref_cast/) crate
> Fix soundness issue in `StringBinding::unchecked_from_js_ref`

- worker-sys/src/types/incoming_request_cf_properties.rs
- worker/src/cf.rs
This PR updates the `IncomingRequestCfProperties` to reflect that `as_organization` is optional.
We ran into a case today in production where `cf.asOrganization` was `undefined`.
We're not using `worker` directly, but we are using bindings based on `worker-sys`, which resulted in the Worker panicking when trying to call the `as_organization` method.
I posted a [question](https://discord.com/channels/595317990191398933/1394398763119804528) about this in the Cloudflare Developers Discord and was told that this field can be optional and its presence should not be assumed:
> Make `as_organization` optional on `IncomingRequestCfProperties`

- worker/src/durable.rs
- worker/src/r2/mod.rs
- worker/src/websocket.rs
The warnings in question:
```
warning: hiding a lifetime that's elided elsewhere is confusing
--> worker/src/durable.rs:80:25
|
80 |     pub fn id_from_name(&self, name: &str) -> Result<ObjectId> {
|                         ^^^^^                        ^^^^^^^^ the same lifetime is hidden here
|                         |
|                         the lifetime is elided here
|
= help: the same lifetime is referred to in inconsistent ways, making the signature confusing
= note: `-D mismatched-lifetime-syntaxes` implied by `-D warnings`
= help: to override `-D warnings` add `#[allow(mismatched_lifetime_syntaxes)]`
help: use `'_` for type paths
|
80 |     pub fn id_from_name(&self, name: &str) -> Result<ObjectId<'_>> {
|                                                              ++++ …
```
> Fix "hiding a lifetime that's elided elsewhere is confusing" warnings on the Nightly compiler

- .github/workflows/pullrequest.yml
- .gitmodules
- Cargo.lock
- Cargo.toml
- package.json
- worker-build/src/wasm_pack/install/mod.rs
This includes wasm-bindgen as a submodule in workers-rs, and updates the build calls to correctly reference it.
This allows us to easily test new wasm-bindgen releases and PRs ahead of time.
> wasm bindgen submodule support

- worker-build/src/main.rs
Fixes a bug in worker-build where we were trying to remove the `snippets` folder when snippets were not used resulting an an error.
> fix snippets handling when not using snippets

- .github/workflows/pullrequest.yml
- worker-build/src/main.rs
This was deprecated in the change to the wasm-bindgen module target, but we need to retain support for backwards compat until the official deprecation can be made (and alternative mechanisms for RPC bindings are provided).
Replaces https://github.com/cloudflare/workers-rs/pull/829.
> fix keeping support for CUSTOM_SHIM
